//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCamMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxMainChannelSettingsFileText {
            get {
                return ((string)(this["textBoxMainChannelSettingsFileText"]));
            }
            set {
                this["textBoxMainChannelSettingsFileText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxChannelBaseLinkText {
            get {
                return ((string)(this["textBoxChannelBaseLinkText"]));
            }
            set {
                this["textBoxChannelBaseLinkText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxSettingsDataTableText {
            get {
                return ((string)(this["textBoxSettingsDataTableText"]));
            }
            set {
                this["textBoxSettingsDataTableText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxLinkText {
            get {
                return ((string)(this["textBoxLinkText"]));
            }
            set {
                this["textBoxLinkText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxLoadChannelsChecked {
            get {
                return ((bool)(this["checkBoxLoadChannelsChecked"]));
            }
            set {
                this["checkBoxLoadChannelsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxStartChannelsChecked {
            get {
                return ((bool)(this["checkBoxStartChannelsChecked"]));
            }
            set {
                this["checkBoxStartChannelsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonLoadAllChannelsChecked {
            get {
                return ((bool)(this["radioButtonLoadAllChannelsChecked"]));
            }
            set {
                this["radioButtonLoadAllChannelsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonLoadLoadedChannelsChecked {
            get {
                return ((bool)(this["radioButtonLoadLoadedChannelsChecked"]));
            }
            set {
                this["radioButtonLoadLoadedChannelsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonStartAllChannelsChecked {
            get {
                return ((bool)(this["radioButtonStartAllChannelsChecked"]));
            }
            set {
                this["radioButtonStartAllChannelsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonStartLoadedChannelsChecked {
            get {
                return ((bool)(this["radioButtonStartLoadedChannelsChecked"]));
            }
            set {
                this["radioButtonStartLoadedChannelsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxMonitorLayoutsFolderText {
            get {
                return ((string)(this["textBoxMonitorLayoutsFolderText"]));
            }
            set {
                this["textBoxMonitorLayoutsFolderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tabControlMonitorsSelectedIndex {
            get {
                return ((int)(this["tabControlMonitorsSelectedIndex"]));
            }
            set {
                this["tabControlMonitorsSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int listBoxSettingsPagesSelectedIndex {
            get {
                return ((int)(this["listBoxSettingsPagesSelectedIndex"]));
            }
            set {
                this["listBoxSettingsPagesSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxOtherChannelSettingsFileText {
            get {
                return ((string)(this["textBoxOtherChannelSettingsFileText"]));
            }
            set {
                this["textBoxOtherChannelSettingsFileText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxChannelSnapshotFolderText {
            get {
                return ((string)(this["textBoxChannelSnapshotFolderText"]));
            }
            set {
                this["textBoxChannelSnapshotFolderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxPlayerSnapshotFolderText {
            get {
                return ((string)(this["textBoxPlayerSnapshotFolderText"]));
            }
            set {
                this["textBoxPlayerSnapshotFolderText"] = value;
            }
        }
    }
}
